# configs/config.yaml

project:
  name: "exp1"
  version: "0.9.15"
  seed: 42


carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  map: "Town10HD"
  dt: 0.1 
  sync_mode: true
  spectator:
    location: {x: -60.227, y: 25.511, z: 14.917}
    rotation: {pitch: -34.466, yaw: 39.638, roll: 0.000}



mpc:
  horizon: 1    # planning horizon: T
  num_samples: 10  
  sim_start: 5     # in second
  sim_end: 12

  w_safe: 10
  w_control: 1

  hard: True


stl:
  pedestrian: 2.0   # in meter
  ambulance: 5.0
  parked_v1: 1.5
  parked_v2: 1.5


ego_vehicle:
  # spawn params
  blueprint: "vehicle.tesla.model3"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 40
  spawn:
    location: {x: -45.214, y: 70.322, z: 1}
    rotation: {pitch: -2.933, yaw: -87.606, roll: 0.000}
  destination:
    location: {x: -45.214, y: -3.398, z: 1}
    rotation: {pitch: -3.156, yaw: -85.004, roll: 0.000}

  # dynamics params obtained from utils.py
  lr: 1.50
  acc_min: -10
  acc_max: 6
  beta_min: -0.5
  beta_max: 0.5
  width: 2.16   
  length: 4.79 

  warmup: 0.4


ambulance:
  blueprint: "vehicle.ford.ambulance"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 45
  spawn:
    location: {x: -45.146, y: 90.043, z: 2.194}
    rotation: {pitch: -5.294, yaw: -89.380, roll: 0.000}
  destination:
    location: {x: -45.654, y: 3.146, z: 2.324}
    rotation: {pitch: -6.836, yaw: -89.509, roll: 0.000}

  lr: 1.88
  acc_min: -8
  acc_max: 4
  beta_min: -0.5
  beta_max: 0.5
  width: 2.35   
  length: 6.37 

  proximity: 3
  std_acc: 0.1
  std_steer: 0.02

  warmup: 0.95


pedestrian:
  spawn:
    location: {x: -36.011, y: 36.775, z: 1.640}
    rotation: {pitch: -8.565, yaw: 178.503, roll: 0.000}

  mean_speed: 5
  std_speed: 1
  std_dir: 0.05
  

parked_v1:
  blueprint: "vehicle.mini.cooper_s"  
  spawn:
    location: {x: -41.153, y: 43.561, z: 2.117}
    rotation: {pitch: -8.757, yaw: -89.587, roll: 0.000}
  width: 1.97  
  length: 3.81 


parked_v2:
  blueprint: "vehicle.audi.a2"
  spawn:
    location: {x: -41.153, y: 48.561, z: 2.117}
    rotation: {pitch: -8.757, yaw: -89.587, roll: 0.000}
  width: 1.79  
  length: 3.71


paths:
  log_dir: "./logs"

