# configs/config.yaml

project:
  name: "STL_MOO_exp1"
  version: "0.9.15"
  seed: 42


carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  map: "Town10HD"
  dt: 0.05 
  sync_mode: true
  spectator:
    location: {x: -60.227, y: 25.511, z: 14.917}
    rotation: {pitch: -34.466, yaw: 39.638, roll: 0.000}


mpc:
  T: 1
  sim_start: 4
  sim_end: 9


ego_vehicle:
  # spawn params
  blueprint: "vehicle.tesla.model3"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 40
  spawn:
    location: {x: -45.214, y: 70.322, z: 1}
    rotation: {pitch: -2.933, yaw: -87.606, roll: 0.000}
  destination:
    location: {x: -39.752, y: -3.398, z: 1}
    rotation: {pitch: -3.156, yaw: -85.004, roll: 0.000}

  # dynamics params
  lr: 1.41
  acc_min: -8
  acc_max: 4
  beta_min: -0.5
  beta_max: 0.5
  width: 1.85   
  length: 4.70 


ambulance:
  # spawn params
  blueprint: "vehicle.ford.ambulance"
  autopilot: True
  draw_route: False
  behavior: "aggressive"
  target_speed: 45
  spawn:
    location: {x: -45.146, y: 90.043, z: 2.194}
    rotation: {pitch: -5.294, yaw: -89.380, roll: 0.000}
  destination:
    location: {x: -45.654, y: 3.146, z: 2.324}
    rotation: {pitch: -6.836, yaw: -89.509, roll: 0.000}

  # other params
  proximity: 3
  std_acc: 0.1
  std_steer: 0.02


pedestrian:
  mean_speed: 4
  std_speed: 1
  std_dir: 0.1
  spawn:
    location: {x: -36.011, y: 36.775, z: 1.640}
    rotation: {pitch: -8.565, yaw: 178.503, roll: 0.000}


parked_vehicles:
  blueprints: 
    - "vehicle.mini.cooper_s"
    - "vehicle.audi.a2"
  spawn:
    location: {x: -41.153, y: 43.561, z: 2.117}
    rotation: {pitch: -8.757, yaw: -89.587, roll: 0.000}
  gap: 6


paths:
  carla_root: "./CARLA_0.9.15"
  data_dir: "./data"
  output_dir: "./data/output"
  log_dir: "./data/logs"
  checkpoint_dir: "./data/checkpoints"
