# params for initializing the experiment

project:
  name: "Highway Crash Avoidance"
  seed: 42
  exp: "exp2"

carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  map: "Town04"
  dt: 0.1 
  sync_mode: true
  spectator:
    location: {x: -282.375, y: 7.686, z: 13.805}
    rotation: {pitch: -25.180, yaw: 0.857, roll: 0.000}

mpc:
  horizon: 2             
  num_samples: 30
  num_prob: 15        
  sim_start: 3.5
  emergency_start: 5.5     
  sim_end: 10
  type: "pareto"
  density: 2

stl:
  d_safe_x: 5.0
  d_safe_y: 3.0
  d_crash: 1
  d_ped: 2
  a_comfort: -4
  beta_rate_max: 0.2

  x_min: -346.205
  x_max: -156.287
  y_min: 4.102
  y_max: 14.067

  crash_x_min: -259.097
  crash_x_max: -248.818
  crash_y_min: 5.105
  crash_y_max: 7.822

ego_vehicle:
  blueprint: "vehicle.tesla.model3"
  autopilot: True
  draw_route: False
  behavior: "aggressive"
  target_speed: 60
  spawn:
    location: {x: -165.657, y: 5.447, z: 8.040}
    rotation: {pitch: -15.836, yaw: -180.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}
  lr: 1.50            # dynamics params obtained from utils.py
  acc_min: -6
  acc_max: 6
  beta_min: -0.262    # beta_max = 0.262 (≈15.0°) → δ = 28.6°  → steer_max = 0.408
  beta_max: 0.262 
  width: 2.16   
  length: 4.79 
  warmup: 0.5

leader:
  blueprint: "vehicle.dodge.charger_2020"
  autopilot: True
  draw_route: False
  behavior: "aggressive"
  target_speed: 60
  spawn:
    location: {x: -180.657, y: 5.447, z: 8.040}
    rotation: {pitch: -15.836, yaw: -180.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}
  std_acc: 0.1
  std_steer: 0.005

follower:
  blueprint: "vehicle.audi.etron"
  autopilot: True
  draw_route: False
  behavior: "aggressive"
  target_speed: 60
  spawn:
    location: {x: -145.657, y: 5.447, z: 12.040}
    rotation: {pitch: -15.836, yaw: -180.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}
  std_acc: 0.1
  std_steer: 0.005

left_vehicle:
  blueprint: "vehicle.mercedes.coupe_2020"
  autopilot: True
  draw_route: False
  behavior: "aggressive"
  target_speed: 60
  spawn:
    location: {x: -155.657, y: 8.447, z: 8.040}
    rotation: {pitch: -15.836, yaw: -180.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 8.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}
  std_acc: 0.1
  std_steer: 0.005

collision_v1:
  blueprint: "vehicle.nissan.patrol_2021"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 0
  spawn:
    location: {x: -255.862, y: 6.375, z: 3.150}
    rotation: {pitch: -6.056, yaw: -175.498, roll: 0.000}

collision_v2:
  blueprint: "vehicle.toyota.prius"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 0
  spawn:
    location: {x: -250.862, y: 6.375, z: 3.150}
    rotation: {pitch: -6.056, yaw: -175.498, roll: 0.000}

pedestrian1:
  blueprint: "walker.pedestrian.0001"
  spawn:
    location: {x: -256.862, y: 4.775, z: 3.150}
    rotation: {pitch: -6.056, yaw: 0, roll: 0.000}
  mean_speed: 4
  std_speed: 1.5
  std_dir: 0.1

pedestrian2:
  blueprint: "walker.pedestrian.0002"
  spawn:
    location: {x: -250.862, y: 4.775, z: 3.150}
    rotation: {pitch: -6.056, yaw: -178.498, roll: 0.000}
  mean_speed: 2
  std_speed: 1
  std_dir: 0.05









