# params for initializing the experiment

project:
  name: "multi-agent collision avoidance at highway"
  seed: 42
  exp: "exp2"

carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  map: "Town04"
  dt: 0.1 
  sync_mode: true
  spectator:
    location: {x: -200.503, y: 10.774, z: 20.530}
    rotation: {pitch: -26.282, yaw: -178.128, roll: 0.000}

mpc:
  horizon: 2             
  num_samples: 100        
  sim_start: 13    
  sim_end: 8
  type: "pareto"
  density: 1

stl:
  pedestrian: 3   
  ambulance: 5

ego_vehicle:
  blueprint: "vehicle.tesla.model3"
  autopilot: True
  draw_route: True
  behavior: "aggressive"
  target_speed: 60
  spawn:
    location: {x: -120.657, y: 5.447, z: 12.040}
    rotation: {pitch: -15.836, yaw: -172.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}
  lr: 1.50            # dynamics params obtained from utils.py
  acc_min: -10
  acc_max: 6
  beta_min: -0.262    # beta_max = 0.262 (≈15.0°) → δ = 28.6°  → steer_max = 0.408
  beta_max: 0.262 
  width: 2.16   
  length: 4.79 
  warmup: 0.5

leader:
  blueprint: "vehicle.dodge.charger_2020"
  autopilot: True
  draw_route: True
  behavior: "normal"
  target_speed: 60
  spawn:
    location: {x: -130.657, y: 5.447, z: 12.040}
    rotation: {pitch: -15.836, yaw: -172.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}

follower:
  blueprint: "vehicle.audi.etron"
  autopilot: True
  draw_route: True
  behavior: "normal"
  target_speed: 60
  spawn:
    location: {x: -105.657, y: 5.447, z: 12.040}
    rotation: {pitch: -15.836, yaw: -172.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 6.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}

left_vehicle:
  blueprint: "vehicle.mercedes.coupe_2020"
  autopilot: True
  draw_route: True
  behavior: "normal"
  target_speed: 60
  spawn:
    location: {x: -110.657, y: 8.447, z: 12.040}
    rotation: {pitch: -15.836, yaw: -172.304, roll: -0.000}
  destination:
    location: {x: -280.862, y: 8.375, z: 3.150}
    rotation: {pitch: -2.102, yaw: -86.557, roll: 0.000}

collision_v1:
  blueprint: "vehicle.nissan.patrol_2021"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 0
  spawn:
    location: {x: -255.862, y: 6.375, z: 3.150}
    rotation: {pitch: -6.056, yaw: -175.498, roll: 0.000}

collision_v2:
  blueprint: "vehicle.toyota.prius"
  autopilot: True
  draw_route: False
  behavior: "normal"
  target_speed: 0
  spawn:
    location: {x: -250.862, y: 6.375, z: 3.150}
    rotation: {pitch: -6.056, yaw: -175.498, roll: 0.000}

pedestrian1:
  blueprint: "walker.pedestrian.0001"
  spawn:
    location: {x: -253.862, y: 4.775, z: 3.150}
    rotation: {pitch: -6.056, yaw: 0, roll: 0.000}
  mean_speed: 4
  std_speed: 1.5
  std_dir: 0.1

pedestrian2:
  blueprint: "walker.pedestrian.0002"
  spawn:
    location: {x: -252.862, y: 4.775, z: 3.150}
    rotation: {pitch: -6.056, yaw: -175.498, roll: 0.000}
  mean_speed: 4
  std_speed: 1.5
  std_dir: 0.1









